### ISSUE TITLE
Folder Issues

### ISSUE THREAD

**Issue by Four-Study** [UBCDingXin/DDRE_Sampling_GANs#2]
Hi Mr Ding,

I think  I might find a small issue regarding to your code. For each "main" subscript under every subfolder, you created a variable called "wd", which directs to the folder itself or the folder exists only on your PC. I cloned the repository and find out I cannot run any of them unless I change it. I might be wrong. Thanks for your time and attention. 

Youhui

**Comment by UBCDingXin** [comment]
Hi,

Thanks a lot for your interest in our work. 

We deliberately let each folder be a separate experiment, and we went to each folder (such as "./DDRE_Sampling_GANs/Simulation") to run the experiment instead of running it in the root directory.

**Comment by Four-Study** [comment]
I appreciate your answer but I am still a little confused. Yes, I understand you want them to be separated. For example, if you are in 'Simulation/', the main.py says 'wd='./Simulation''. Since there is no './Simulation' under 'Simulation' itself, I have to go to the root folder and run 'python Simulation/main.py' to make it work. That is a little bit inconvenient. Also, 'wd = '/home/xin/OneDrive/Working_directory/DDRE_Sampling_GANs/MNIST'' in 'MNIST/PreTrainCNN.py' directs to an absolute path on your PC. It does not work on other computers. Again, I might miss something. Thanks for any suggestions.

**Comment by UBCDingXin** [comment]
> 

Actually, wd in our original experiment was set as the absolute path of the location of the folder, e.g., "wd ='/home/xin/OneDrive/Working_directory/DDRE_Sampling_GANs/Simulation'" or  'wd = '/home/xin/OneDrive/Working_directory/DDRE_Sampling_GANs/MNIST''' which are the location of Simulation and MNIST  in my computer. To run our code, you may need to replace these absolute paths with the location of the experiment folder on your own computer or server.

**Comment by Four-Study** [comment]
Got it. Thanks for your quick response. Will do as you suggested.
